### ISSUE TITLE
Bug: Deploy job not found

### ISSUE THREAD

**Issue by leolindoso** [nnsnodnb/circleci-orbs-firebase-app-distribution#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Orb version

0.1.0

### Current behavior

Hey, I've followed the example code from the Orb doc page but I keep getting this same error message:

> Cannot find a definition for job named firebase-app-distribution/deploy

### Minimum reproduction config

version: 2.1

orbs:
  unity: game-ci/unity@1.3.0
  node: circleci/node@5.0.2
  firebase-app-distribution: nnsnodnb/firebase-app-distribution@0.1.0

workflows:
  build-unity-project:
    jobs:
      - set-build-version
      - unity/build:
          name: 'android-build'
          step-name: 'Build Android'
          unity-license-var-name: 'UNITY_ENCODED_LICENSE'
          unity-username-var-name: 'UNITY_USERNAME'
          unity-password-var-name: 'UNITY_PASSWORD'
          executor:
            name: 'unity/ubuntu'
            target_platform: 'android'
            editor_version: '2020.3.21f1'
            resource_class: 'large'
          build-target: Android
          compress: false
          context: Context
      - firebase-app-distribution/deploy:
          app: YOUR Firebase App ID
          binary_path: ./path/to/binary.ipa
          groups: nnsnodnb
          release_note: Working in progress application. Please your feedback!
          service_credentials_file: ./path/to/google_service_account.json

### Other

I'd like to use your Orb cause Circle.CI is stopping me from installing firebase tools globally in custom Jobs. So i had to search for alternatives and found your Orb

**Comment by nnsnodnb** [comment]
Thank you for issue creation and use this.

This Orb doesn't have `job`. But that has deploy `command`.

**Comment by leolindoso** [comment]
Sorry, but since it doesn't have a Job, i think that the example shown at the documentation can be a little misleading. Also, do you have any example on how to call deploy command?

**Comment by nnsnodnb** [comment]
Oops. Thank you for tell me:bow:
